# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Non-transitive R classes for faster builds
android.nonTransitiveRClass=true

# Enable build cache
org.gradle.caching=true

# Parallel execution
org.gradle.parallel=true
