import type { ThermalConfig } from "./config.js";

/**
 * Builds the CUPS PPD for a thermal queue.
 *
 * The PPD routes PDF and PostScript to the `cuppa-thermal` filter; CUPS then
 * advertises those formats to clients, so macOS, iOS and Android send a PDF
 * rather than a raster the printer could not understand.
 */

function mmToPoints(mm: number): number {
  return Math.round((mm / 25.4) * 72);
}

export function buildThermalPpd(config: ThermalConfig, label: string): string {
  const widthPt = mmToPoints(config.labelWidthMm);
  const heightPt = mmToPoints(config.labelHeightMm);
  const pageName = `w${widthPt}h${heightPt}`;
  const res = `${config.dpi}dpi`;

  return `*PPD-Adobe: "4.3"
*% Generated by Cuppa for ${label}
*FormatVersion: "4.3"
*FileVersion: "1.0"
*LanguageVersion: English
*LanguageEncoding: ISOLatin1
*PCFileName: "CUPPA.PPD"
*Manufacturer: "Cuppa"
*Product: "(Thermal)"
*ModelName: "Cuppa Thermal (${config.dialect.toUpperCase()})"
*ShortNickName: "Cuppa Thermal"
*NickName: "Cuppa Thermal ${config.dialect.toUpperCase()}"
*PSVersion: "(3010.000) 0"
*LanguageLevel: "3"
*ColorDevice: False
*DefaultColorSpace: Gray
*FileSystem: False
*Throughput: "1"
*LandscapeOrientation: Plus90
*TTRasterizer: Type42

*OpenUI *Resolution/Output Resolution: PickOne
*OrderDependency: 10 AnySetup *Resolution
*DefaultResolution: ${res}
*Resolution ${res}/${config.dpi} DPI: "<</HWResolution[${config.dpi} ${config.dpi}]>>setpagedevice"
*CloseUI: *Resolution

*OpenUI *PageSize/Media Size: PickOne
*OrderDependency: 10 AnySetup *PageSize
*DefaultPageSize: ${pageName}
*PageSize ${pageName}/${label}: "<</PageSize[${widthPt} ${heightPt}]/ImagingBBox null>>setpagedevice"
*CloseUI: *PageSize

*OpenUI *PageRegion: PickOne
*OrderDependency: 10 AnySetup *PageRegion
*DefaultPageRegion: ${pageName}
*PageRegion ${pageName}/${label}: "<</PageSize[${widthPt} ${heightPt}]/ImagingBBox null>>setpagedevice"
*CloseUI: *PageRegion

*DefaultImageableArea: ${pageName}
*ImageableArea ${pageName}/${label}: "0 0 ${widthPt} ${heightPt}"

*DefaultPaperDimension: ${pageName}
*PaperDimension ${pageName}/${label}: "${widthPt} ${heightPt}"

*cupsFilter2: "application/pdf application/vnd.cuppa.thermal 0 cuppa-thermal"
*cupsFilter2: "application/postscript application/vnd.cuppa.thermal 0 cuppa-thermal"
*% End of PPD
`;
}
